### ISSUE TITLE
Activator not compatible with lejos

### ISSUE THREAD

**Issue by Pepich** [typesafehub/activator#1032] opened 2015-05-30 22:01 UTC
I'll try my best to give a good description on what exactly is wrong and what I discovered so far, if I'm missing any information or did something wrong please hint me so I can fix it, thanks :)

The Problem is activator not launching with the following error message: '"\leJOS" kann syntaktisch an dieser Stelle nicht verarbeitet werden.'

Happens for every command except for "help" - help gets dealt with in the .bat file so it obviously runs properly but it just won't start up the activator. I am aware of the fact that I put up a german sentence there so here's a translation: '"\leJOS" is syntactic an unprocesseable term at this position.'. What is lejos? Lejos NXJ is a way to program the lego mindstorms series using java. I don't see any other origin for that error to appear than lejos.

Neither the minimal nor the big version worked (yes I tried both, even tho the big one just has a few libraries added by default which the minimal is totally missing out on). The Version I tried to use is 1.3.2. Neither 32-bit nor 64-bit java worked. The first entry in my path variable is the link towards the java jdk location so it shouldn't even bother trying to find any other entries. And every other java application runs fine so far.

System specs software wise are (maybe not nessecary but they won't hurt anyone):

OS is Windows 7 x64 Home Premium SP 1
Java version is either:
jdk1.7.0_51 (64-bit) or jdk1.7.0_51 (32-bit)
PATH starts with "C:\Program Files\Java\jdk1.7.0_51\bin" (even though it does not say it's missing java I thought it might be helpful)

launching the activator-jar file directly from the command prompt resolves in the same error. I tried everything I could think of to find a solution but it looks like something really strange is going on there...

**Comment by jsuereth** [comment] 2015-06-05 14:58
What is your user name and user home directory?

**Comment by jsuereth** [comment] 2015-08-12 14:41
Also, this may be a duplicate of: #1043

**Closed by jsuereth** 2015-08-12 14:41 UTC
