### ISSUE TITLE
Activator UI: Failed to load sbt configuration (Windows)

### ISSUE THREAD

**Issue by hstm** [typesafehub/activator#1037] opened 2015-06-04 08:47 UTC
Hi,

I'm trying to run some of the example projects in the latest activator release (1.3.4), but build fails with the error message "Failed to load sbt configuration".

The issue is independent from the template I use. Activator always shows the same sequence of info messages:

- Waiting for sbt server to restart
- Loading sbt configuration
- Failed to load sbt configuration

This seems to be a Windows only issue, since everything works fine in my Ubuntu 14.04 VM.

OS: Windows 8.1 Enterprise 64 bit
JDK: java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
installed in: C:\Program Files\Java\jdk1.8.0_45 (but there's no difference if I install Java in C:\Java)

Activator install path: C:\Users\Helge\Development\bin\activator-1.3.4

The error message is:

```
request pending until connection to sbt opens: RequestExecution(1,Some(compile))
    Opened sbt at 'C:\Users\Helge\Development\projects\src\reactive-stocks'
    sending request to sbt RequestExecution(1,Some(compile))
    sbt server socket logs are in: C:\Users\Helge\Development\projects\src\reactive-stocks\.sbtserver\connections\master.log
    sbt client logs are in: C:\Users\Helge\Development\projects\src\reactive-stocks\.sbtserver\connections\activator-0a9efcaf-ae89-479e-bdce-868788b66e9c.log
    sbt general server logs are in: C:\Users\Helge\Development\projects\src\reactive-stocks\.sbtserver\master.log
    > --initialize
    > initialize
    > onFailure load-failed
    > boot
    > reload
    [Loading] Scanning directory C:\Users\Helge\Development\projects\src\reactive-stocks\project
    [Loading] Found non-root projects 
    [Loading] Done in C:\Users\Helge\Development\projects\src\reactive-stocks\project, returning: ()
    deducing auto plugins based on known facts Set(Atom(sbt.plugins.CorePlugin)) and clauses Clauses(List(Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(sbt.plugins.JUnitXmlReportPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.CorePlugin),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(sbt.plugins.IvyPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.JUnitXmlReportPlugin)))))
      :: deduced result: Matched(sbt.plugins.CorePlugin,sbt.plugins.IvyPlugin,sbt.plugins.JvmPlugin,sbt.plugins.JUnitXmlReportPlugin)
    sorting: ns: List(sbt.plugins.CorePlugin, sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.JUnitXmlReportPlugin)
      :: sorting:: found: List(sbt.plugins.CorePlugin) not found List(sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.JUnitXmlReportPlugin)
      :: sorting:: found: List(sbt.plugins.CorePlugin, sbt.plugins.IvyPlugin) not found List(sbt.plugins.JvmPlugin, sbt.plugins.JUnitXmlReportPlugin)
      :: sorting:: found: List(sbt.plugins.CorePlugin, sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin) not found List(sbt.plugins.JUnitXmlReportPlugin)
      :: sorting:: found: List(sbt.plugins.CorePlugin, sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.JUnitXmlReportPlugin) not found List()
      :: sorted deduced result: List(sbt.plugins.CorePlugin, sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.JUnitXmlReportPlugin)
    [Loading] Done in C:\Users\Helge\Development\projects\src\reactive-stocks\project, returning: (reactive-stocks-build)
    URI has an authority component
    java.lang.IllegalArgumentException: URI has an authority component
    Use 'last' for the full log.
    > load-failed
    Failed to load project.
    > server-wait-for-reboot
```

This error also occurs if I execute sbt from command line:

```
C:\Users\Helge>sbt
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; sup
port was removed in 8.0
java.lang.IllegalArgumentException: URI has an authority component
        at java.io.File.<init>(File.java:423)
        at sbt.Classpaths$.sbt$Classpaths$$bootRepository(Defaults.scala:1758)
        at sbt.Classpaths$$anonfun$appRepositories$1.apply(Defaults.scala:1729)
        at sbt.Classpaths$$anonfun$appRepositories$1.apply(Defaults.scala:1729)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike
.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike
.scala:244)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimize
d.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)

        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at sbt.Classpaths$.appRepositories(Defaults.scala:1729)
        at sbt.Classpaths$$anonfun$41.apply(Defaults.scala:1102)
        at sbt.Classpaths$$anonfun$41.apply(Defaults.scala:1102)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
        at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.
apply$mcV$sp(INode.scala:69)
        at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
        at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] java.lang.IllegalArgumentException: URI has an authority component
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

 If I delete the folder C:\Users\Helge\.sbt, sbt executes without any error, so maybe the error is caused by an incorrect path in the sbt repository?

```
[repositories]
  local
  activator-launcher-local: file://${activator.local.repository-${activator.home-${user.home}/.activator}/repository}, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  activator-local: file://${activator.local.repository-//C:/Users/Helge/Development/bin/activator-1.3.4/repository}, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  maven-central
  typesafe-releases: http://repo.typesafe.com/typesafe/releases
  typesafe-ivy-releasez: http://repo.typesafe.com/typesafe/ivy-releases, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
```

**Comment by hstm** [comment] 2015-06-05 05:21
Checked out the reference to https://github.com/sbt/sbt/issues/2044. Changing the file URIs from file:// to file:/// in the sbt repository (C:\Users\<username>\.sbt) definitely works if I make them before loading a project and while the activator ui is running, But these changes are being overwritten everytime I restart the activator ui.

**Comment by jsuereth** [comment] 2015-06-05 14:57
duplicate of #1033

**Closed by jsuereth** 2015-06-05 14:57 UTC

**Comment by aleksandarbosancic** [comment] 2015-08-30 21:41
+1 Windows 8.1 Pro issue exists.

**Comment by deltavee** [comment] 2015-08-31 17:32
yep -- windows 7 Ent as well

**Comment by molavec** [comment] 2015-09-01 18:10
1+ on Windows 7 32-bits Pro Edition

**Comment by stevewillcock** [comment] 2015-09-04 10:48
This also happens on Windows 10 64 bit Professional - the same fix seems to work

**Comment by corruptmemory** [comment] 2015-09-04 13:49
I'm working on addressing this in the next release of Activator.  Sorry for all the trouble.

**Comment by stefan-hoehn** [comment] 2015-09-05 11:43
This seems to be fixed in "activator.bat" with 

rem We add a / in front, so we get file:///C: instead of file://C:
rem Java considers the later a UNC path.
rem We also attempt a solid effort at making it URI friendly.
rem We don't even bother with UNC paths.
set JAVA_FRIENDLY_HOME_1=/!ACTIVATOR_HOME:\=/!
set JAVA_FRIENDLY_HOME=/!JAVA_FRIENDLY_HOME_1: =%%20!

However, if you use the Gitbash on Windows (10) it then uses "activator" and still fails (make_url() does not seem to fix this).

Any ideas how to solve that?

**Comment by stevewillcock** [comment] 2015-09-05 13:43
For clarification, after reading Stefan's comment here, I did indeed see the issue after running activator from git bash on Windows. This issue may therefore only appear when using git bash as Stefan indicates. I don't have Windows on this machine so I can't verify that it works in my case when using cmd right now unfortunately.

**Comment by chriso153** [comment] 2015-10-18 04:31
This may still be a slight problem. I just installed activator for the first time on my Windows 10 computer. I used the minimal-akka-scala-seed template to create a project. It would not build because of the error in this case. I copied my repositories file here.

----

    [repositories]
      local
      activator-launcher-local: file://${activator.local.repository-${activator.home-${user.home}/.activator}/repository}, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
      activator-local: file://${activator.local.repository-//C:/Users/Chris/Downloads/typesafe-activator-1.3.6/activator-dist-1.3.6/repository}, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
      maven-central
      typesafe-releases: http://repo.typesafe.com/typesafe/releases
      typesafe-ivy-releasez: http://repo.typesafe.com/typesafe/ivy-releases, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]

----

But then, I stopped activator and restarted it. Activator changed the 2 file:// lines to file://// and now the project compiles correctly. No matter how many times I now restart activator, the file has 4 slashes in the files lines (copied) below. So, I guess it's only on a brand new install that the problem exists. Stopping and restarting seems to resolve it.

----
    [repositories]
      local
      activator-launcher-local: file:////${activator.local.repository-${activator.home-${user.home}/.activator}/repository}, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
      activator-local: file:////${activator.local.repository-C:/Users/Chris/Downloads/typesafe-activator-1.3.6/activator-dist-1.3.6//repository}, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
      maven-central
      typesafe-releases: http://repo.typesafe.com/typesafe/releases
      typesafe-ivy-releasez: http://repo.typesafe.com/typesafe/ivy-releases, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]

----

**Comment by corruptmemory** [comment] 2015-10-19 16:12
The issue is that Activator needs to write different URIs depending on platform.  For Windows we need  `file:////` and for everyone else we need `file://` because of ambiguity with UNC paths.

It is possible that some of the alternative shells mess-up detecting you're running under windows.

The quick work-around is to delete the lines with `activator-launcher-local` and `activator-local`.  If your version of Activator needs them they will get regenerated.

**Comment by stefan-hoehn** [comment] 2015-10-28 17:06
@corruptmemory : Thanks: the workaround does work for me.

**Comment by krishna81m** [comment] 2016-05-11 05:23
Thanks the `~./sbt/ file:////` change worked for me on Windows 7, latest sbt
