### ISSUE TITLE
play-akka-angular-websocket template doesn't work on Java 8

### ISSUE THREAD

**Issue by eximius313** [typesafehub/activator#821] opened 2014-12-26 12:02 UTC
error: error while loading CharSequence, class file 'C:\Program Files\Java\jdk1.8.0_25\jre\lib\rt.jar(java/lang/CharSequence.class)' is broken

What can I do?
Kind regards

**Comment by henrikengstrom** [comment] 2015-02-27 16:21
Hello @eximius313 
Sorry for the late response!
Try deleting ``.activator`` in your home folder and see if that helps.

**Comment by henrikengstrom** [comment] 2015-03-23 17:33
Closing this issue as there has been no feedback. Hopefully the issue is resolved.

**Closed by henrikengstrom** 2015-03-23 17:33 UTC
Labels: pending feedback
