### ISSUE TITLE
Getting Futures timed out after [5 seconds] error when creating new projects

### ISSUE THREAD

**Issue by patrickliangli** [typesafehub/activator#1010] opened 2015-04-22 18:00 UTC
I am getting an *Futures timed out after [5 seconds]* error when creating new projects with Activator. The project **does** get created with all the contents from the selected template despite the error, but just wondering why this is happening.

I am not behind a proxy (direct internet connection), and the template content is getting pulled down properly (I think). I tried to nuke the .activator directory to start fresh, but that made no difference.

I have looked around and found a few people having the same issue, but couldn't find a solution for it. It will be good to be able to fix this error as I am demoing the tool to other devs and having this error is not helping making the case :(

```
Patricks-MacBook-Pro-2:test lulumomo$ ~/Applications/activator-1.3.2/activator new test-java minimal-java

Fetching the latest list of templates...

OK, application "test-java" is being created using the "minimal-java" template.

To run "test-java" from the command line, "cd test-java" then:
/Users/lulumomo/Projects/appfusions/samples/test/test-java/activator run

To run the test for "test-java" from the command line, "cd test-java" then:
/Users/lulumomo/Projects/appfusions/samples/test/test-java/activator test

To run the Activator UI for "test-java" from the command line, "cd test-java" then:
/Users/lulumomo/Projects/appfusions/samples/test/test-java/activator ui

java.util.concurrent.TimeoutException: Futures timed out after [5 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:116)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:116)
	at activator.ActivatorCli$.activator$ActivatorCli$$generateProjectTemplate(ActivatorCli.scala:147)
	at activator.ActivatorCli$$anonfun$apply$1$$anonfun$13$$anonfun$apply$3.apply(ActivatorCli.scala:105)
	at activator.ActivatorCli$$anonfun$apply$1$$anonfun$13$$anonfun$apply$3.apply(ActivatorCli.scala:104)
	at scala.Option.map(Option.scala:146)
	at activator.ActivatorCli$$anonfun$apply$1$$anonfun$13.apply(ActivatorCli.scala:104)
	at activator.ActivatorCli$$anonfun$apply$1$$anonfun$13.apply(ActivatorCli.scala:103)
	at scala.Option.flatMap(Option.scala:171)
	at activator.ActivatorCli$$anonfun$apply$1.apply$mcI$sp(ActivatorCli.scala:103)
	at activator.ActivatorCli$$anonfun$apply$1.apply(ActivatorCli.scala:19)
	at activator.ActivatorCli$$anonfun$apply$1.apply(ActivatorCli.scala:19)
	at activator.ActivatorCli$.withContextClassloader(ActivatorCli.scala:179)
	at activator.ActivatorCli$.apply(ActivatorCli.scala:19)
	at activator.ActivatorLauncher.run(ActivatorLauncher.scala:37)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
Patricks-MacBook-Pro-2:test lulumomo$ 
```

I am running Java 1.7
```
Patricks-MacBook-Pro-2:test lulumomo$ java -version
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)
Patricks-MacBook-Pro-2:test lulumomo$ 
```

**Comment by havocp** [comment] 2015-04-23 19:53
This should be fixed by https://github.com/typesafehub/activator/pull/1012

**Comment by havocp** [comment] 2015-04-24 14:13
The reason everyone just started seeing this was that we broke the dns config for https://typesafe.com (vs. https://www.typesafe.com) and activator uses the apex domain. We reverted that for the moment so this should be "fixed" for now (but I'll still leave in the fix to ignore errors here, since breaking the server for this shouldn't be a fatal error to activator).

**Closed by havocp** 2015-04-24 14:13 UTC

**Comment by damianball** [comment] 2015-04-24 21:06
I've tested out the fix on my end. It works perfectly. Thanks!

**Comment by papajo** [comment] 2015-05-26 18:42
I am getting this error while creating a new project. So what is the solution for this?

**Comment by corruptmemory** [comment] 2015-05-26 19:09
@papajo, there is a new 1.3.3 version of Activator out.  You may want to try that version to see if the problem is still occurring.
