### ISSUE TITLE
Activator UI tutorial hangs 

### ISSUE THREAD

**Issue by xevix** [typesafehub/activator#1035] opened 2015-06-02 03:09 UTC
Scala: 2.11
Activator: 1.3.2

1. Run `activator ui`
2. Try creating tutorial "Play Framework using Macwire for dependency injection"
3. Hangs forever with the below

```
Your application is being opened
This will just take a minute...

Template is cloned, compiling project definition...
```

Console Output shows nothing:

```
$ activator ui
Local repository: activator-launcher-local @ file:/usr/local/Cellar/typesafe-activator/1.3.2/libexec/repository
Local repository: activator-local @ file:/usr/local/Cellar/typesafe-activator/1.3.2/libexec/repository
Play server process ID is 51802
[info] play - Application started (Prod)
[info] play - Listening for HTTP on /127.0.0.1:8888
[info] a.e.s.Slf4jLogger - Slf4jLogger started
```

**Comment by henrikengstrom** [comment] 2015-06-02 07:52
Hello @xevix,
Could this be network related? I just tried the exact same thing and it works for me.
Can you please make sure you're connected to the internet and retry the process.
Thanks,
Henrik

**Comment by xevix** [comment] 2015-06-03 06:10
@henrikengstrom It turns out the network/project I'm on was using Artifactory/Ivy and it wasn't working well. Removing that and having it go straight to the default repos seems to be working.

**Comment by henrikengstrom** [comment] 2015-06-03 06:21
Great. Closing this one then. 
Thanks for using Activator.

**Closed by henrikengstrom** 2015-06-03 06:21 UTC

**Comment by xevix** [comment] 2015-06-13 09:24
@henrikengstrom It's happening again, this time from a different machine with no SBT repositories set. It just hangs indefinitely. What information can I provide to help with this?

**Comment by Centaur** [comment] 2015-07-23 10:11
This still happens in activator 1.3.5  

Reproduce: 

```bash
$ mkdir tmp
$ cd tmp
$ activator new test
$ cd test
$ activator ui # will freeze after `Slf4jLogger started`, no browser opened
$ cd ~
$ activator ui # browser will be opened
```

**Comment by jagadeeshpb** [comment] 2017-01-05 11:09
Any updates on this issue? I'm facing the same issue with 1.3.12. behind the proxy and I think s3.amazonaws.com is diabled. But I dont see any errors in the console. But the UI shows "Compiling Project definition..." and nothing happens
