### ISSUE TITLE
Running activator breaks subsequent invocations of sbt

### ISSUE THREAD

**Issue by deanwampler** [typesafehub/activator#968] opened 2015-02-26 16:40 UTC
I ran activator 1.3.0 (UI) on an sbt project, which worked fine. After stopping it, I ran sbt and got this:

```
⌁ [deanwampler:~/projects/spark/spark-workshop] master(+3/-0)+* ± sbt
java.net.URISyntaxException: Illegal character in authority at index 7: file://${activator.home}/repository
  at java.net.URI$Parser.fail(URI.java:2848)
  at java.net.URI$Parser.parseAuthority(URI.java:3186)
  at java.net.URI$Parser.parseHierarchical(URI.java:3097)
  at java.net.URI$Parser.parse(URI.java:3053)
  at java.net.URI.<init>(URI.java:588)
  at java.net.URL.toURI(URL.java:939)
  at sbt.Resolver$url$.apply(Resolver.scala:269)
  at sbt.Classpaths$.sbt$Classpaths$$bootRepository(Defaults.scala:1658)
  at sbt.Classpaths$$anonfun$appRepositories$1.apply(Defaults.scala:1634)
  at sbt.Classpaths$$anonfun$appRepositories$1.apply(Defaults.scala:1634)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
  at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
  at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
  at scala.collection.AbstractTraversable.map(Traversable.scala:105)
  at sbt.Classpaths$.appRepositories(Defaults.scala:1634)
  at sbt.Classpaths$$anonfun$41.apply(Defaults.scala:1052)
  at sbt.Classpaths$$anonfun$41.apply(Defaults.scala:1052)
  at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
  at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
  at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
  at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
  at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
  at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
  at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:744)
[error] java.net.URISyntaxException: Illegal character in authority at index 7: file://${activator.home}/repository
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

After much poking around, I noticed `~/.sbt/repositories` had been updated recently. Here's what it contained:

```
[repositories]
  local
  activator-launcher-local: file://${activator.local.repository-${activator.home}/repository}, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  activator-local: file://${activator.local.repository-/Users/deanwampler/projects/activator/activator-1.3.0/repository}, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  maven-central
  typesafe-releases: http://repo.typesafe.com/typesafe/releases
  typesafe-ivy-releasez: http://repo.typesafe.com/typesafe/ivy-releases, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
```

I renamed this file to `~/.sbt/repositories.toss` and then sbt started successfully.

**Comment by rcavalcanti** [comment] 2015-02-27 10:01
Removing ~/.sbt/repositories solve indeed the problem, but it'll come back as soon you launch activator on again.
An alternative is to always run 'activator' instead of 'sbt'.

@henrikengstrom any idea of how we can workaround it without having to delete the repositories file?

**Comment by havocp** [comment] 2015-02-27 13:19
Ugh. @jsuereth this obviously doesn't work how we would like and drop the entire entry when the system props are unset. How can we fix it?

**Comment by henrikengstrom** [comment] 2015-02-27 13:20
Hey @rcavalcanti,
Long time no see - hope everything's fine! I hope to see you at Scala Days in Amsterdam in June :)

I will take a look at this issue today. I have only seen it on Windows before and I thought we already had a fix for it! No known workaround at this point I am afraid.
What OS are you on? Does it happen all the time when you run ``activator`` and thereafter ``sbt``?
Cheers,
Henrik

**Comment by havocp** [comment] 2015-02-27 13:25
Hmm, I bet the windows fix actually broke this, because now there's no fallback to user.home on mac/linux.
https://github.com/typesafehub/activator/commit/66f12b4db61eaee83c96890557cc651c509bd379
apparently when there's no fallback sbt just keeps the literal `${activator.home}` or something???

**Comment by rcavalcanti** [comment] 2015-02-27 13:26
I'm using Mac OSX and it happens all the time. Once you run activator the .sbt/repositories file is modified as @deanwampler mentioned.

I have many functions on my shell that cd on projects and launch sbt, so I don't want to modify them all. So, my workaround is: alias sbt='activator'

ps: @henrikengstrom I'll be at Scala Days Amsterdam, but will pass SF. See you there!

**Comment by havocp** [comment] 2015-02-27 13:35
I bet we can add a default to some nonexistent directory name, if activator.home is unset, in the same way we defaulted to user.home before.

**Comment by havocp** [comment] 2015-02-27 13:49
We are having trouble reproducing this, so speculate it's OS-dependent or sbt-version-dependent. Can anyone who sees this tell us:

 * version of sbt in project/build.properties for the project in question
 * version of sbt-launch.jar
 * what "sbt" script you have that runs sbt-launch.jar
 * OS and OS version

**Comment by havocp** [comment] 2015-02-27 13:59
OK, I got it to reproduce. For me it does NOT happen if project/build.properties has 0.13.7 or 0.13.8-M4. It DOES happen if project/build.properties has 0.13.5 or 0.13.6. So there was some change in sbt itself.

I am using the sbt 0.13.5 launcher on Linux with a trivial wrapper script.

**Comment by deanwampler** [comment] 2015-02-27 13:59
I installed sbt with HomeBrew and use its supplied bash script and jar
file:

`/usr/local/bin/sbt --version` prints 0.13.6

Same version in `project/build.properties`.

OSX Yosemite (10.10.2)



On Fri, Feb 27, 2015 at 7:49 AM, Havoc Pennington <notifications@github.com>
wrote:

> We are having trouble reproducing this, so speculate it's OS-dependent or
> sbt-version-dependent. Can anyone who sees this tell us:
>
>    - version of sbt in project/build.properties for the project in
>    question
>    - version of sbt-launch.jar
>    - what "sbt" script you have that runs sbt-launch.jar
>    - OS and OS version
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/typesafehub/activator/issues/968#issuecomment-76396710>
> .
>



-- 
*Dean Wampler, Ph.D.*
Typesafe <http://typesafe.com>
Author: Programming Scala, 2nd Edition
<http://shop.oreilly.com/product/0636920033073.do> (O'Reilly)
@deanwampler <http://twitter.com/deanwampler>



I'm speaking at Software Architecture Conference | March 16-19, 2015
http://bit.ly/17rCi7S #OreillySACon

I'm speaking at Strata + Hadoop World London | May 5-7, 2015
http://strataconf.com/big-data-conference-uk-2015 #strataconf

**Comment by rcavalcanti** [comment] 2015-02-27 14:03
I have:
sbt installed via homebrew (v. 0.13.7)
projects I tried were all on 0.13.5 (project/build.properties)

OSX Yosemite (10.10.2)

**Comment by jsuereth** [comment] 2015-02-27 14:04
It looks like the homebrew version of sbt must be using sbt-extras which does wonky things with the launcher that we do not want it to do.

You must be using a 0.13.7+ launcher feature, although I don't recall those having changed.   ON OSX, if you use our bundled launchers, you should be ok (as long as the 0.13.7 launcher is used instead of the 0.13.5).  CHeck to make sure your script isn't swapping launchers on you.

**Comment by jsuereth** [comment] 2015-02-27 14:05
ALSO, it looks like this is a failure in the URI parse if ${activator.home} doesn't exist, so it may just be something that happens all the time....

**Comment by havocp** [comment] 2015-02-27 14:06
@jsuereth project/build.properties doesn't change the launcher thought right? this error seems to be post-launch, when evaluating bootRepository

**Comment by rcavalcanti** [comment] 2015-02-27 14:07
Fair enough!
Does that mean that homebrew formulas are not maintained by Typesafe?

**Comment by jsuereth** [comment] 2015-02-27 14:08
exactly.  Howeer, that's not the right fix, just figured it out.

**Comment by jsuereth** [comment] 2015-02-27 14:09
the repositories file needsa  new default, e.g.

```
[repositories]
  local
  activator-launcher-local: file://${activator.local.repository-${activator.home}/repository}, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  activator-local: file://${activator.local.repository-/Users/deanwampler/projects/activator/activator-1.3.0/repository}, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  maven-central
  typesafe-releases: http://repo.typesafe.com/typesafe/releases
  typesafe-ivy-releasez: http://repo.typesafe.com/typesafe/ivy-releases, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
```

becomes

```
[repositories]
  local
  activator-launcher-local: file://${activator.local.repository-${activator.home-/some/bad/default}/repository}, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  activator-local: file://${activator.local.repository-/Users/deanwampler/projects/activator/activator-1.3.0/repository}, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  maven-central
  typesafe-releases: http://repo.typesafe.com/typesafe/releases
  typesafe-ivy-releasez: http://repo.typesafe.com/typesafe/ivy-releases, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
```

**Comment by henrikengstrom** [comment] 2015-02-27 14:09
I will create a PR with the fix and it will be shipped in 1.3.1 which hopefully is released in a day or two.

**Comment by havocp** [comment] 2015-02-27 14:15
I think this commit hides the problem on sbt 0.13.7 and later: https://github.com/sbt/sbt/commit/a857ae275905c5d75a4abae03b901a9981f6aa2c

**Comment by deanwampler** [comment] 2015-02-27 14:19
I upped two repos to from 0.13.6 to 0.13.7 and now they both work fine, with the Homebrew sbt. I can run with activator, then run with sbt.

**Comment by henrikengstrom** [comment] 2015-02-27 14:46
We will release 1.3.1 today and it contains a fix for this. Closing the ticket now.
Thanks.

**Closed by henrikengstrom** 2015-02-27 14:46 UTC
Labels: bug, candidate for next release
